SITE_TITLE: Tyler Butler
SITE_URL: 'http://tylerbutler.com'
SITE_DESCRIPTION: tylerbutler.com

ENGINE_DIR: engineer
DRAFT_DIR: drafts
TEMPLATE_DIR: templates
STATIC_DIR: static
STATIC_URL: /static

LOADERS: [Local]
