SITE_TITLE: Engineer Site
HOME_URL: '/'
SITE_URL: http://localhost:8080

PUBLISH_DRAFTS: no
POST_DIR:
  - posts
  - archives

THEME_SETTINGS:
  typekit_id: vty2qol
  twitter_id: tylerbutler
  tweet_count: 4

POST_TIMEZONE: 'America/Los_Angeles'
